/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import java.awt.Cursor;
import javax.swing.Timer;

/**
 *
 * @author pecen
 */
public class End extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(End.class.getName());

    /**
     * Creates new form Konec
     */
    private int koncneTocke;
    private int preziveteSekunde;
    private int stopnjaa;
    public End(int tocke, int sekunde, int stopnja) {
        initComponents();
        this.koncneTocke = tocke;
        this.preziveteSekunde = sekunde;
        this.stopnjaa = stopnja;
        jLabel3.setText("Score: " + koncneTocke); 
        jLabel4.setText("Survived for: " + preziveteSekunde + " s");
        if(stopnja == 1) {
            jLabel6.setText("Dificulty: EASY");
        }else if(stopnja == 2) {
            jLabel6.setText("Dificulty: MEDIUM");
        }else {
            jLabel6.setText("Dificulty: HARD");
        }
        animirajOzadje();
        getContentPane().setComponentZOrder(jLabel1, getContentPane().getComponentCount() - 1);
    }

    private void animirajOzadje() {
        Timer timer = new Timer(50, new java.awt.event.ActionListener() {
            int smer = -1; // Začnemo z negativno smerjo (v levo)
            int x = 0;     // Začetna pozicija

            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                x += smer;

                // Mejni vrednosti: -20 (konec levo) in 0 (začetek desno)
                if (x <= -200) {
                    smer = 1;  // Dosegli smo levi rob, zdaj gremo desno proti 0
                } else if (x >= 0) {
                    smer = -1; // Vrnjeni na začetku, gremo spet v levo
                }

                // Nastavi novo lokacijo jLabel1
                jLabel1.setLocation(x, 0);
            }
        });
        timer.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KONEC IGRE");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE RESULTS");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jButton2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, 30));

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("the results will be saved to a file");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("sssssss");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 440, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("by clicking the button");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SCORE:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 450, -1));

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SURVIVED FOR:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 450, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("END OF THE GAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/uvodna.jpg"))); // NOI18N
        jLabel1.setToolTipText("null");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(514, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        dispose();
        new Main_page().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        shraniPodatke(stopnjaa);
    }//GEN-LAST:event_jButton1MouseClicked

    private void shraniPodatke(int stopnja) {
        long trenutniCas = System.currentTimeMillis();
        int pretekleSekunde = (int) ((trenutniCas - preziveteSekunde) / 1000);
        if(stopnja == 1) {
            String zapis = "Date: " + new java.util.Date() + 
                       " | Dificulty: Easy" + 
                       " | Score: " + koncneTocke + "\n";
            try (java.io.FileWriter fw = new java.io.FileWriter("rezultati.txt", true);
             java.io.BufferedWriter bw = new java.io.BufferedWriter(fw)) {

            bw.write(zapis);
            javax.swing.JOptionPane.showMessageDialog(this, "Success!");

            } catch (java.io.IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error saving: " + e.getMessage());
                logger.log(java.util.logging.Level.SEVERE, "Error writing to file", e);
            }
        }else if(stopnja == 2) {
            String zapis = "Date: " + new java.util.Date() + 
                       " | Dificulty: Medium" + 
                       " | Score: " + koncneTocke + "\n";
            try (java.io.FileWriter fw = new java.io.FileWriter("rezultati.txt", true);
             java.io.BufferedWriter bw = new java.io.BufferedWriter(fw)) {

            bw.write(zapis);
            javax.swing.JOptionPane.showMessageDialog(this, "Success!");

            } catch (java.io.IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error saving: " + e.getMessage());
                logger.log(java.util.logging.Level.SEVERE, "Error writing to file", e);
            }
        }else {
            String zapis = "Date: " + new java.util.Date() + 
                       " | Dificulty: Hard" + 
                       " | Score: " + koncneTocke + "\n";
            try (java.io.FileWriter fw = new java.io.FileWriter("rezultati.txt", true);
             java.io.BufferedWriter bw = new java.io.BufferedWriter(fw)) {

            bw.write(zapis);
            javax.swing.JOptionPane.showMessageDialog(this, "Success!");

            } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error saving: " + e.getMessage());
            logger.log(java.util.logging.Level.SEVERE, "Error writing to file", e);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new End(0, 0, 0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
